### ISSUE TITLE
Dependency on 'serverless/lib/plugins/aws/lib/validate' is not in package.json

### ISSUE THREAD

**Issue by dancrumb** [funkybob/serverless-s3-deploy#1]
Version 0.2.1 has a dependency on the .../validate module, but it's not listed in package.json.

As a result, I'm getting:

```
Error --------------------------------------------------
 
     Cannot find module 'serverless/lib/plugins/aws/lib/validate'
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
 
     Please report this error. We think it might be a bug.
 
  Your Environment Information -----------------------------
     OS:                 darwin
     Node Version:       6.9.1
     Serverless Version: 1.8.0
```

**Comment by dancrumb** [comment]
I'm using the global version of `serverless`

**Comment by dancrumb** [comment]
Works fine if I install serverless locally to my project

**Comment by funkybob** [comment]
Ah, nice spot.  Actually, I don't think the code needs validate at all.. I will review this tonight and see if I can update it to BCP.

I've never understood this fetish of Node users to install everything globally...

**Comment by dancrumb** [comment]
Lol... Generally, it's a bad idea, but serverless has some global
functionality and is positioned as a utility rather than a library, soooo
:shrug:

**Comment by funkybob** [comment]
Can you please test the latest code?  If that works fine for you, I'll cut a release.

**Comment by funkybob** [comment]
@dancrumb has this issue been fixed in head?

**Comment by dancrumb** [comment]
Yup - seems to work just fine
And to be explicit, I remove my local serverless from the project to be sure :D
