### ISSUE TITLE
Feature Request: Run after a regular deploy

### ISSUE THREAD

**Issue by arabold** [funkybob/serverless-s3-deploy#12]
First, let me thank you for this plugin. It's actually exactly what I'm looking for.

However, is there a reason why you don't run automatically after every `sls deploy`? When deploying a mixed backend/frontend web application I don't want to "forget" deploying my scripts to S3, too. So having it in a single command would be great. Any thoughts on this?

**Comment by funkybob** [comment]
I'd be happy to make it a configurable...

In my projects using it I found I rarely deployed both front and back end at the same time.

**Comment by funkybob** [comment]
Could you please test the code in the auto-deploy branch?

It requires modifying your config layout slightly [older layouts will be adjusted, but you can't access the auto flag without changing]

Additionally I added a per-target 'prefix' ... naughty to add two features at once, I know, but I was there...

**Comment by arabold** [comment]
Tested and works like a charm. Thanks a lot!
