### ISSUE TITLE
Does not like running on windows

### ISSUE THREAD

**Issue by gemmell** [funkybob/serverless-s3-deploy#15]
Uploaded, but where it should have created subdirectories it's just banged the file up there with the folder in the name. I assume it's due to the backslash on windows vs forward slash on linux. 

e.g. a using this plugin it's put the resources up there but with the key `font-awesome\css\font-awesome.min.css` (instead of creating subfolders).

**Comment by berlinguyinca** [comment]
I'm having the same issue, is there maybe an update available to solve this? Otherwise it sadly renders the plugin unusable for windows users.

**Comment by funkybob** [comment]
I have no windows machines to test on.

I do almost no Node development, either, so I don't know what the de facto solution to supporting platform-dependent path separators is.

I was hoping someone else who does use Windows would have had some input on this... clearly not :/
