### ISSUE TITLE
0.5.0 on NPM doesn't include the promised updates

### ISSUE THREAD

**Issue by arabold** [funkybob/serverless-s3-deploy#24]
Please tell me it's just me and some weird configuration I have locally, but if I check out the latest and greatest 0.5.0 of this repo, it doesn't include my pull request from yesterday. It's _should_ be in there but it seems that the version that was published to NPM is missing the code changes. It only updated the `package.json` 😕

**Comment by arabold** [comment]
Stupid me... You didn't release a new version yet. I was confused. Ignore this bug.

**Comment by funkybob** [comment]
I think I just published v0.6.0 :)
