### ISSUE TITLE
Does not work on Windows, backslash vs forward slash problem

### ISSUE THREAD

**Issue by Hyperkettu** [funkybob/serverless-s3-deploy#30]
When uploading resources, it should have created subdirectories, but it just puts the files in the bucket with the folder in the name. This is probably related to backslash on windows vs forward slash on linux. 

This seems to have been fixed on the repository. However, it has not been published yet as a NPM package update. I would need that fix right away. Could someone publish it? Thanks.

**Comment by funkybob** [comment]
Have you verified that current master _does_ work on Windows?  I have not any Windows machines to test on.
If you can confirm, I'll publish immediately [assuming my flight doesn't leave first]

**Comment by funkybob** [comment]
I just published v0.7.0! Enjoy!

**Comment by Hyperkettu** [comment]
It worked! Thank you!
