### ISSUE TITLE
Feature request: disable resource referencing

### ISSUE THREAD

**Issue by marcoreni** [funkybob/serverless-s3-deploy#31]
Hello,

I'm trying to use this plugin to deploy a packaged artifact to S3 without executing any deploy.

I'm encountering an issue where the plugin tries to list the resources of my Cloudformation Stack, but I don't actually have a CloudFormation stack.

Can this be disabled via an option value?

**Comment by bigluck** [comment]
Me too :(

**Comment by marcoreni** [comment]
Hey @funkybob , any chance on getting #34 merged?

**Comment by funkybob** [comment]
TBH I never understood the reference resolving to start with, so I don't know why it would or wouldn't be needed.

I'll merge and release later today.

Anyone want to take over this project?
