### ISSUE TITLE
not uploading files for serverless versions newer than 1.32.0

### ISSUE THREAD

**Issue by giorgio-zamparelli** [funkybob/serverless-s3-deploy#38]
I've tried to upgrade from serverless 1.32.0 to the following versions but the assets aren't being uploaded to the S3 bucket:
1.33.2
1.34.1
1.35.1
1.36.3
1.37.1
1.38.0

So 1.32.0 seems to be the latest version of serverless with which this plugin works.
Can anyone confirm that it has been using a version older than serverless 1.32.0 with serverless-s3-deploy successfully?

serverless.yml config
```"bundlesS3BucketName": "bundles-${self:provider.stage}",
      "assets": {
            "auto": true,
            "targets": [{
                "bucket": "${self:custom.bundlesS3BucketName}",
                "files": [{
                    "source": "./bundles-${self:provider.stage}",
                    "globs": ["**/*.css", "**/*.css.map", "**/*.js", "**/*.js.map", "**/*.png"]
                }]
            }]
        },```

**Comment by mikestaub** [comment]
This plugin works https://github.com/k1LoW/serverless-s3-sync

**Comment by claabs** [comment]
I narrowed the issue down to this serverless PR breaking this plugin: https://github.com/serverless/serverless/pull/5349

This thread has some solutions for solving the problem from the plugin's end: https://github.com/marcy-terui/serverless-alexa-skills/issues/24

**Comment by claabs** [comment]
Whoops, my bad. I was still on 0.7.0. It looks like 0.8.0 fixed it for me.

**Comment by giorgio-zamparelli** [comment]
Using serverless 1.54.0 and this issue is not appearing anymore. Going to close this issue.
