### ISSUE TITLE
Add eslint support

### ISSUE THREAD

**Issue by dancrumb** [funkybob/serverless-s3-deploy#4]
What do you think about adding eslint support? I think it would have caught that `new Promise.resolve()` issue... Maybe 😬

I'm happy to make a PR for it

**Comment by funkybob** [comment]
Please, by all means! I'm fairly new to the JS ecosystem, so would like to see how it's done :)

**Comment by funkybob** [comment]
Just did a basic approach myself.  Welcome feedback.
