### ISSUE TITLE
Propose you publish 0.3.0

### ISSUE THREAD

**Issue by dancrumb** [funkybob/serverless-s3-deploy#9]
So, maybe it's worth publishing 0.3.0

I suggest a minor bump since it's a large piece of new function, but it's a non-breaking change (and generally a major bump, to 1.0.0, implies a breaking change).

What do you think?

**Comment by funkybob** [comment]
This message arrived _just_ after I did that :)

**Comment by dancrumb** [comment]
oops! you forgot to bump the version in `package.json`.

Not sure if you know this, but `npm version <major|minor|patch>` on a clean repo will update package.json, commit the change and tag the commit. Then all you need to do is push the commit and the tag and then run `npm publish`.

Sorry if you already know this... don't mean to be "that guy" :/

**Comment by funkybob** [comment]
Odd... I did use the npm version command to do it, and it's showing as 0.3.0 here, on GH, and in npm... where are you not seeing it?

**Comment by dancrumb** [comment]
\*cough\* in my forked repo \*cough\*

*exits sideways*
